# Data {#data}


This chapter describes the datasets used throughout the book, one possibility
is that this could be moved to an appendix and in the online version of the
book any mention of the dataset in the main text
could be cross-linked to its description. One
thing that I really liked in the first edition is the emphasis on analysis
question of interest and the little notes about the data. I believe the
original layout was to put the data in order of appearance of the book, which
naturally clusters them by technique.


| Name             | Description                                                                                        | Source                                                                                                | Proposed Chapter                                | Other Notes                                                                                                                                                                                     |
|------------------|----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|-------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| pdfsense         | Physics data that is featured heavily in Ursula's work                                             | https://metapdf.hepforge.org/PDFSense/                                                                | clustering, classification                      | An update to prim7                                                                                                                                                                              |
| pedestrian       | Melbourne pedestrian counts                                                                        | rwalkr                                                                                                | multivariate time series, regression (?)        | It could be turned into a multivariate time  series with the addition of weather information.                                                                                                   |
| mouseretina      | Single cell RNA-seq data from Macosko et al.                                                       | Available in scRNAseq package on Bioconductor                                                         | dimension, clustering                           | Used in the liminal paper,  one concern is that there a lot of nuances to processing the data that might need to be explained.  An updated version of the arabidopsis expression data from 1e.  |
| pisa             | OECD programme for international student assessment data                                           | Di has data                                                                                           | regression                                      | would need to check usage agreements                                                                                                                                                            |
| sketches         | Google's Quickdraw data                                                                            | https://quickdraw.withgoogle.com/                                                                     | neural networks, classification                 |                                                                                                                                                                                                 |
| mosquitos        | An audio "civic science" dataset containing wingbeat  frequencies for classifying mosquito species | https://elifesciences.org/articles/27854; https://datadryad.org/stash/dataset/doi:10.5061/dryad.98d7s | neural networks, classification (forests / LDA) |                                                                                                                                                                                                 |
| aklhouseprices   | Auckland house prices collected by Earo                                                            | Earo has data                                                                                         | regression, toolbox                             | would need to check usage agreements                                                                                                                                                            |
| books            | A text dataset would be a more modern example, like those in 1010.                                 |                                                                                                       | dimension, clustering                           |                                                                                                                                                                                                 |
| wages            | An updated version of the wages dataset                                                            | Di is working on this I think                                                                         | regression, toolbox, multivariate time series   |                                                                                                                                                                                                 |
| bushfires        | The data Di used in her conversation article                                                       | Di has data                                                                                           | toolbox, forests                                |                                                                                                                                                                                                 |
| clusterchallenge | Simulated data used to show various cluster examples                                               | Available in liminal                                                                                  | clustering                                      |                                                                                                                                                                                                 |
| duolingo         | Learning traces for duolingo users                                                                 | https://github.com/duolingo/halflife-regression                                                       | regression, forests                             | CCBY                                                                                                                                                                                            |
|                  |                                                                                                    |                                                                                                       |                                                 |                                                                                                                                                                                                 |
|                  |                                                                                                    |                                                                                                       |                                                 |                                                                                                                                                                                                 |

There were fifteen datasets listed in chapter 7 of the first edition. Several
of these were related to networks which we are not including this time. I have
tried to give a mix of things on a variety of topics. It would be nice to
see if there's updated versions of the "tips" 
(there seems to be a lot of noise in the literature here and no open datasets) and 
Di's music data (perhaps we could scrape our own spotify accounts to get an equivalent), there are also a few audio challenge datasets like [FSD50K](https://zenodo.org/record/4060432#.YCHksxMzbWY) . I think
it would be useful to have more unstructured data sets like natural text that we have used for 1010.


### Other possible sources for data

There are now many search engines available for datasets that originate
from research contexts that list licensing information and DOIs:

* https://zenodo.org (mostly ecology/biology)
* https://datadryad.org/stash (mostly biology)
* https://dataverse.harvard.edu/dataverse/harvard/ (mostly social sciences, but has a mixture of things)
