project:
  type: book
execute:
  freeze: true
  
book:
  title: "Interactively exploring high-dimensional data and models in R"
  author: "Dianne Cook and Ursula Laa"
  date: today
  page-footer:
    left: |
      Interactively exploring high-dimensional data and models in R was written by 
      Dianne Cook and Ursula Laa.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  cover-image: cover.png
  favicon: cover.png
  site-url: https://dicook.github.io/mulgar_book/
  repo-url: https://github.com/dicook/mulgar_book
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
        - 1-intro.qmd
        - 2-notation.qmd
    - references.qmd

bibliography: [book.bib, packages.bib]
csl: apa.csl
nocite: |
  @*

format:
  html:
    theme: 
      - cosmo
      - style.scss
    code-fold: true
    classoption: fleqn
    code-link: true

  pdf:
    documentclass: book
    include-in-header: 
      text: |
        \usepackage{amsmath}
        \usepackage{blkarray}
        \usepackage{imakeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
    pdf-engine: pdflatex
    keep-tex: true
    collapse: true
    knitr:
      opts_chunk:
        out.width: 80%
        R.options:
          width: 62