project:
  type: book
  output-dir: docs

book:
  title: "Interactive and dynamic graphics for high-dimensional data using R"
  author: "Dianne Cook and Ursula Laa"
  date: "July 1, 2023"
  page-navigation: true
  cover-image: cover.png
  favicon: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - part: dimension.qmd
      chapters: 
        - dimension-overview.qmd
        - pca.qmd
        - nldr.qmd
    - part: unsupervised.qmd
      chapters: 
        - unsupervised-overview.qmd
        - brush-and-spin.qmd
        - hierarchical-clustering.qmd
        - kmeans-clustering.qmd
        - model-based-clustering.qmd
        - som.qmd
        - unsupervised-summary.qmd
    - part: supervised.qmd
      chapters: 
        - LDA.qmd
        - forests.qmd
        - svm.qmd
        - nn.qmd
        - misclassifications.qmd
    - part: temporal.qmd
      chapters: 
        - multivariate-time-series.qmd
    - references.qmd
  appendices:    
    - toolbox.qmd
    - data.qmd
    - glossary.qmd

bibliography: [book.bib, packages.bib]
nocite: |
  @*
  
format:
  html:
    theme: 
      - cosmo
      - style.scss
    code-fold: true
    css: style.css
    classoption: fleqn
  pdf:
    documentclass: scrreport
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \usepackage{amsmath}
        \usepackage{blkarray}
        \makeindex
    include-after-body: 
      text: |
        \printindex