project:
  type: book
  output-dir: docs
execute:
  freeze: true
  
book:
  title: "Interactively exploring high-dimensional data and models in R"
  author: "Dianne Cook and Ursula Laa"
  date: "August 14, 2023"
  page-footer:
    left: |
      Interactively exploring high-dimensional data and models in R was written by 
      Dianne Cook and Ursula Laa.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  cover-image: cover.png
  favicon: cover.png
  site-url: https://dicook.github.io/mulgar_book/
  repo-url: https://github.com/dicook/mulgar_book
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
        - 1-intro.qmd
        - 2-notation.qmd
    - part: "Dimension reduction"
      chapters: 
        - 3-intro-dimred.qmd
        - 4-pca.qmd
        - 5-nldr.qmd
    - part: "Cluster analysis"
      chapters: 
        - 6-intro-clust.qmd
        - 7-spin-and-brush.qmd
        - 8-hierarchical.qmd
        - 9-kmeans.qmd
        - 10-model-based.qmd
        - 11-som.qmd
        - 12-summary-clust.qmd
    - part: "Supervised classification"
      chapters: 
        - 13-intro-class.qmd
        - 14-lda.qmd
        - 15-forests.qmd
        - 16-svm.qmd
        - 17-nn.qmd
        - 18-summary-class.qmd
    - part: "Miscellaneous"
      chapters: 
        - 19-mv-time-series.qmd
    - references.qmd
  appendices:    
    - A1-toolbox.qmd
    - A2-data.qmd
    - A3-book_code_and_data.qmd
    - A4-glossary.qmd

bibliography: [book.bib, packages.bib]
csl: apa.csl
nocite: |
  @*
  
format:
  html:
    theme: 
      - cosmo
      - style.scss
    code-fold: true
    classoption: fleqn
    code-link: true

  pdf:
    documentclass: book
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \usepackage{amsmath}
        \usepackage{blkarray}
        \makeindex
    include-after-body: 
      text: |
        \printindex