project:
  type: book
  output-dir: pdf
execute:
  freeze: true
  
book:
  title: "Interactively exploring high-dimensional data and models in R"
  author: "Dianne Cook and Ursula Laa"
  date: today
  page-footer:
    left: |
      Interactively exploring high-dimensional data and models in R was written by 
      Dianne Cook and Ursula Laa.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  cover-image: cover.png
  favicon: cover.png
  site-url: https://dicook.github.io/mulgar_book/
  repo-url: https://github.com/dicook/mulgar_book
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - 1-intro.qmd
    - 2-notation.qmd
    - 3-intro-dimred.qmd
    - 4-pca.qmd
    - 5-nldr.qmd
    - 6-intro-clust.qmd
    - 7-spin-and-brush.qmd
    - 8-hierarchical.qmd
    - 9-kmeans.qmd
    - 10-model-based.qmd
    - 11-som.qmd
    - 12-summary-clust.qmd
    - 13-intro-class.qmd
    - 14-lda.qmd
    - 15-forests.qmd
    - 16-svm.qmd
    - 17-nn.qmd
    - 18-summary-class.qmd
    - references.qmd
  appendices:    
    - A1-toolbox.qmd
    - A2-data.qmd
    - A3-book-code-and-data.qmd
    - A4-glossary.qmd

bibliography: [book.bib, packages.bib]
csl: apa.csl
nocite: |
  @*

format:
  html:
    theme: 
      - cosmo
      - style.scss
    code-fold: true
    classoption: fleqn
    code-link: true

  pdf:
    documentclass: krantz
    include-in-header: 
      - text: |
          \usepackage{amsmath}
          \usepackage{blkarray}
          \usepackage[most]{tcolorbox}
          \usepackage{xcolor}
          \definecolor{info}{HTML}{CBC988}
          \definecolor{infostripe}{HTML}{EAC024}
          \definecolor{insight}{HTML}{E87C00}
          \definecolor{grey}{RGB}{192, 192, 192}
          \usepackage{imakeidx}
          \makeindex
          \usepackage{float}
          \floatplacement{table}{H}
      - macros.tex
    include-after-body: 
      - text: |
          \printindex
    pdf-engine: pdflatex
    keep-tex: true
    collapse: true
    toc: true
    toc-depth: 2
    toc-title: Contents
    knitr:
      opts_chunk:
        out.width: 80%
        R.options:
          width: 62