project:
  type: book
  output-dir: docs
execute:
  freeze: true
  
book:
  title: "Interactively exploring high-dimensional data and models in R"
  author: "Dianne Cook and Ursula Laa"
  date: "July 1, 2023"
  page-footer:
    left: |
      Interactively exploring high-dimensional data and models in R was written by 
      Dianne Cook and Ursula Laa.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  cover-image: cover.png
  favicon: cover.png
  site-url: https://dicook.github.io/mulgar_book/
  repo-url: https://github.com/dicook/mulgar_book
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
        - intro.qmd
        - notation.qmd
    - part: "Dimension reduction"
      chapters: 
        - dimension-overview.qmd
        - pca.qmd
        - nldr.qmd
    - part: "Cluster analysis"
      chapters: 
        - unsupervised-overview.qmd
        - brush-and-spin.qmd
        - hierarchical-clustering.qmd
        - kmeans-clustering.qmd
        - model-based-clustering.qmd
        - som.qmd
        - unsupervised-summary.qmd
    - part: "Supervised classification"
      chapters: 
        - LDA.qmd
        - forests.qmd
        - svm.qmd
        - nn.qmd
        - misclassifications.qmd
    - part: "Miscellaneous"
      chapters: 
        - multivariate-time-series.qmd
    - references.qmd
  appendices:    
    - toolbox.qmd
    - data.qmd
    - glossary.qmd

bibliography: [book.bib, packages.bib]
csl: apa.csl
nocite: |
  @*
  
format:
  html:
    theme: 
      - cosmo
      - style.scss
    code-fold: true
    css: style.css
    classoption: fleqn
    code-link: true

  pdf:
    documentclass: book
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \usepackage{amsmath}
        \usepackage{blkarray}
        \makeindex
    include-after-body: 
      text: |
        \printindex