### Exercises {.unnumbered}
\addcontentsline{toc}{section}{Exercises}



1. Using the spin and brush method, uncover three clusters in the
\Data{Flea Beetles} data and confirm that these correspond to the
three species. (Hint: Transform the data to principal components and
enter these variables into the projection pursuit guided tour running
the holes index. Also the species should not be identified by color or
symbol, until the clusters have been uncovered.)

2. Run hierarchical clustering with average linkage on the
\Data{Flea Beetles} data (excluding \Vbl{species}).

3. 
    a.  Cut the tree at three clusters and append a cluster id to the dataset. 
How well do the clusters correspond to the species? (Plot
\Vbl{cluster id} vs \Vbl{species}, and use jittering if necessary.)
Using brushing in a plot of \Vbl{cluster id} linked to a tour plot of
the six variables, examine the beetles that are misclassified.

    b. Now cut the tree at four clusters, and repeat the last part.

    c. Which is the better solution, three or four clusters? Why?

3. For the \Data{Italian Olive Oils},
    a. Consider the oils from the four areas of Southern Italy. What
would you expect to be the result of model-based clustering on the
eight fatty acid variables?
   b. Run model-based clustering on the Southern oils, with the goal
of extracting clusters corresponding to the four areas. What is the
best model? Create ellipsoids corresponding to the model and examine
these in a tour. Do they match your expectations?
    c. Create ellipsoids corresponding to alternative models and use
these to decide on a best solution.


4. This question uses the \Data{Rat Gene Expression} data.
    a. Explore the patterns in expression level for the functional
classes. Can you characterize the expression patterns for each class?
    b. How well do the cluster analysis results match the functional
classes? Where do they differ? 
    c. Could you use the cluster analysis results to refine the
classification of genes into functional classes? How would you do
this?

5. In the \Data{Music} data, make further comparisons of the five-cluster
solutions of $k$-means and Ward's hierarchical clustering.
    a. On what tracks do the methods disagree?
    b. Which track does $k$-means consider to be a singleton cluster,
while Ward's hierarchical clustering groups it with 12 other tracks?
    c. Identify and  characterize the tracks in the four clusters where
both methods agree.

6. In the \Data{Music} data, fit a $5\times 5$ grid SOM, and observe the results for 100, 200, 500, and 1,000 updates. How does the
net change with the increasing number of updates?

7. There is a mystery dataset in the collection, called 
\Data{clusters-unknown.csv}. How many clusters are in this dataset?



