# This is the code that sets up libraries and other things for each chapter
library(colorspace)
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(GGally)
library(geozoo)
library(tourr)
library(mulgar)
library(patchwork)
library(GGally)
library(ggthemes)
library(ggrepel)
library(colorspace)
library(datasets)
library(MASS)